
" Settings
set number
syntax on

set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4

set modeline

" Start Vim-Plug
call plug#begin('~/.vim/plugged')

" Solarized Color Scheme
" Plug 'altercation/vim-colors-solarized'
" Solarized 
" Plug 'romainl/flattened'

" Python AutoCompletion
Plug 'Valloric/YouCompleteMe'

" Base16 Color Scheme
Plug 'chriskempson/base16-vim'

" Nerdtree 
Plug 'scrooloose/nerdtree'

" CodiVim
Plug 'metakirby5/codi.vim'

" Thesarus 
Plug 'beloglazov/vim-online-thesaurus', { 'on': ['Thesaurus', 'OnlineThesaurusCurrentWord'] }

" Comments
Plug 'tpope/vim-commentary'

" Git Wrapper
Plug 'tpope/vim-fugitive'

" Distraction free writing 
Plug 'junegunn/goyo.vim'

" Quoting Parenthesizing plugin
Plug 'tpope/vim-surround'


" Python syntax highlighting, pep8 
Plug 'klen/python-mode'


" End Vim-Plug
call plug#end()

" Color Scheme
" colorscheme gruvbox
colorscheme default 
set background=dark
" colorscheme flattened_dark
" let base16colorspace=256

set antialias
set nocompatible

" -- Display
set title " Update the title of your window or your terminal
set number " Display line numbers
set ruler " Display cursor position
set wrap " Wrap lines when they are too long
set scrolloff=3 " Display at least 3 lines around you cursor

" (for scrolling)
" set guioptions=T " Enable the toolbar

" -- Search
set ignorecase " Ignore case when searching
set smartcase " If there is an uppercase in your search term

" search case sensitive again
set incsearch " Highlight search results when typing
set hlsearch " Highlight search results

" -- Beep
" set visualbell " Prevent Vim from beeping
" set noerrorbells " Prevent Vim from beeping

" Backspace behaves as expected
set backspace=indent,eol,start

" Hide buffer (file) instead of abandoning when switching to another buffer
set hidden

filetype on
filetype plugin on
filetype indent on

set list                   " Show non-printable characters.
if has('multi_byte') && &encoding ==# 'utf-8'
  let &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±'
else
  let &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
endif

" Put all temporary files under the same directory.
" https://github.com/mhinz/vim-galore#handling-backup-swap-undo-and-viminfo-files
set backup
set backupdir   =$HOME/.vim/files/backup/
set backupext   =-vimbackup
set backupskip  =
set directory   =$HOME/.vim/files/swap//
set updatecount =100
set undofile
set undodir     =$HOME/.vim/files/undo/
set viminfo ='100,n$HOME/.vim/files/info/viminfo


" Python

" set list listchars=tab:▷⋅,trail:⋅,nbsp:⋅
set statusline=%F%m%r%h%w\ [TYPE=%Y\ %{&ff}]\ \ [%l/%L\ (%p%%)
filetype plugin indent on
au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth=79 " PEP-8 Friendly
